config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  get '/flights', to: 'flights#index'

  resources :bookings,  only: [:create, :show]
  post '/bookings/new', as: 'new_booking' 
end

app/models/airport.rb
class Airport < ApplicationRecord
  before_save :upcase_code
  validates :code, presence: true, length: { is: 3 }

  has_many :departing_flights, class_name:  'Flight', 
                               foreign_key: 'from_airport_id'
  has_many :arriving_flights,  class_name:  'Flight',
                               foreign_key: 'to_airport_id'
  private

    def upcase_code
      code.upcase!
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many   :passengers, inverse_of: :booking, dependent: :destroy

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: 'Airport', foreign_key: 'from_airport_id'
  belongs_to :to_airport,   class_name: 'Airport', foreign_key: 'to_airport_id'

  has_many :bookings, dependent: :destroy
  has_many :passengers, through: :bookings

  validates :from_airport_id, presence: true
  validates :to_airport_id,   presence: true
  validates :datetime,        presence: true
  validates :duration,        presence: true

  def formatted_date
    datetime.strftime("%Y/%m/%d")
  end

  def self.select_dates
    self.pluck("distinct date(datetime)")
  end

  def self.search(search_params)
    date         = search_params[:date].to_datetime
    date_end     = date.tomorrow
    to_airport   = search_params[:to_airport]
    from_airport = search_params[:from_airport]
   
    Flight.where(from_airport_id: from_airport, to_airport_id: to_airport,
                 datetime: date..date_end)
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking, inverse_of: :passengers

  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  
  def new
    @flight    = Flight.find(posted_params[:flight_id])
    @booking   = @flight.bookings.build
    passengers = posted_params[:passengers].to_i
    passengers.times { @booking.passengers.build }
  end

  def create
    @flight  = Flight.find(posted_params[:flight_id])
    @booking = Booking.new(posted_params)
    if @booking.save
      flash[:success] = "Booking created."
      passengers = @flight.passengers
      PassengerMailer.confirmation_email(@flight, @booking, passengers).deliver_now!
      redirect_to @booking
    else
      render :new
    end
  end

  def show
    booking = Booking.find(params[:id])
    @flight     = booking.flight
    @passengers = booking.passengers
  end

  private

    def posted_params
      params.require(:booking).permit(:flight_id, :passengers,
                                      passengers_attributes: [:name, :email])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airports = Airport.all
    @dates    = Flight.order('datetime').map(&:formatted_date).uniq

    unless search_params.empty?
      if search_params[:from_airport] == search_params[:to_airport]
        flash.now[:alert] = "Origin and destination airports cannot be the same."
      else
        @flights = Flight.search(search_params)
      end
    end
  end

  private

    def search_params
      params.permit(:date, :passengers, :from_airport, :to_airport)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.slim
.row.centered
  h3 Book your flight
  = form_for @booking do |f|
      = render 'shared/error_messages', object: f.object
      = f.hidden_field :flight_id
      = label_tag 'Origin'
      = text_field_tag 'origin', @flight.from_airport.code, disabled: true
      = label_tag 'Destination'
      = text_field_tag 'destination', @flight.to_airport.code, disabled: true
      = label_tag 'Date & Time'
      = text_field_tag 'datetime', @flight.datetime, disabled: true
      - count = 1
      = f.fields_for :passengers do |ff|
        = ff.label "#{count.ordinalize} passenger:"
        = ff.text_field :name, placeholder: "Name", required: true, autofocus: true
        = ff.email_field :email, placeholder: "Email", required: true
        - count += 1
      = f.submit "Book now", class: 'button expanded'

app/views/bookings/show.html.slim
h3 Booking Details
h4 Flight ##{@flight.id} from 
  <strong>#{@flight.from_airport.code}</strong> to 
  <strong>#{@flight.to_airport.code}</strong>
p: em Flying on #{@flight.datetime}
h5 Passenger Details:
table
  thead
    tr
      th Name
      th Email
  tbody
    - @passengers.each do |passenger|
      tr 
        td = passenger.name
        td = passenger.email

app/views/flights/index.html.slim
.row.centered
  h3 Search for a flight!
  = form_tag(flights_path, method: :get) do
    = label_tag :from_airport, "Origin:"
    = select_tag(:from_airport, \
                 options_from_collection_for_select(@airports, :id, :code, params[:from_airport]))
    = label_tag :to_airport, "Destination:"
    = select_tag(:to_airport, \
                 options_from_collection_for_select(@airports, :id, :code, params[:to_airport]))
    = label_tag :date, "Date:"
    = select_tag(:date, \
                 options_for_select(@dates, params[:date]))
    = label_tag :passengers, "Number of Passengers:"
    = select_tag(:passengers, options_for_select((1..4).to_a, params[:passengers]))
    = submit_tag("Search", class: 'button expanded large')

.row.centered
  - unless @flights.nil?
    - if @flights.empty?
      h4 No flights found.  Search again.
    - else
      h5: em 
        | For 
        = pluralize(params[:passengers].to_i, 'passenger')
      table
          thead
            tr
              th From:
              th To:
              th Flight Time
              th
          tbody
          - @flights.each do |flight|
            tr
             td = flight.from_airport.code
             td = flight.to_airport.code
             td = flight.datetime
             td
              = form_for(:booking, url: new_booking_url) do |f|
                = f.hidden_field(:flight_id, value: flight.id) 
                = f.hidden_field(:passengers, value: params[:passengers].to_i)
                = f.submit "Book", class: 'button expanded small'

app/views/layouts/_navigation.html.slim
nav.top-bar
  strong: h4 = link_to 'Flight Booker', root_url

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title = content_for?(:title) ? yield(:title) : "Odin Flight Booker"
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/navigation'
    .row
      .medium-6.medium-centered.column
        - flash.each do |message_type, message|
          div class=["callout #{message_type}"]
            em = message
        = yield
    footer.top-bar
      span Chris Norwood | 2016 | 
      span: em: a href="https://github.com/chrisnorwood/odin-flight-booker"
        | Find on Github

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  div
    div
      | The form contains 
      = pluralize(object.errors.count, "error")
      ul
        - object.errors.full_messages.each do |message|
          li = message